spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      stat-view-servlet:
        # druid 登录的 用户名密码
        login-username: admin
        login-password: admin

# mybatis-plus 相关配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/cyg/**/mapper/xml/*.xml
  global-config:
    banner: false
    db-config:
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"), NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      select-strategy: NOT_EMPTY

version: 1

